compressionLevel: mixed

enableGlobalCache: false

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_TOKEN}"
    npmRegistryServer: "https://npm.fontawesome.com/"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
